# Generated by Django 4.2.17 on 2024-12-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
